### ISSUE TITLE
Certificates not trusted on endeavouros (arch based)

### ISSUE THREAD

**Issue by sarvasana** [tmds/linux-dev-certs#23]
After issuing:
`dotnet linux-dev-certs install`

When starting a project:
`The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.`

![image](https://github.com/tmds/linux-dev-certs/assets/2652163/85331d86-4533-4894-a98d-59a4e009672a)

**Comment by tmds** [comment]
> The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.

This is a false warning. It is due to the ASP.NET Core implementation not having an actual check to see if there is a trusted certificate but a hard-coded `IsTrusted(X509Certificate2 certificate) => false;`.

An implementation was added in https://github.com/dotnet/aspnetcore/pull/55335. .NET 9 preview 6+ should no longer print this warning.
